version: '3'
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8087:8087"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=reports-db-user
      - ME_CONFIG_BASICAUTH_PASSWORD=reports-db-password
    restart: always
